name: Build and Test API Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true  # In case you're using Git LFS for large files

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Build Docker Image
        run: docker build -t bgl-log-api .

      - name: Run Docker Container and Test API
        run: |
          docker run -d --name api_container -p 8000:8000 bgl-log-api
          # Wait for the container to start
          sleep 15
          # Test the root endpoint; this will fail the job if the API is not responding
          curl --fail http://localhost:8000/ || exit 1
